# Generated by Django 5.1.15 on 2026-06-18 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('provider_document', 'Provider document'), ('complaint_evidence', 'Complaint evidence'), ('completion_evidence', 'Completion evidence')], max_length=60)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('public_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('uploaded', 'Uploaded'), ('attached', 'Attached'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('attached_entity_type', models.CharField(blank=True, max_length=80)),
                ('attached_entity_id', models.UUIDField(blank=True, null=True)),
                ('upload_expires_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_uploaded_file',
                'indexes': [models.Index(fields=['owner_user', 'purpose', '-created_at'], name='core_upload_owner_u_14ab80_idx'), models.Index(fields=['attached_entity_type', 'attached_entity_id'], name='core_upload_attache_75593f_idx')],
            },
        ),
    ]
