# Generated by Django 5.1.15 on 2026-06-17 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('company', 'Company')], max_length=30)),
                ('display_name', models.CharField(max_length=160)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=30)),
                ('verification_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prov_provider',
            },
        ),
        migrations.CreateModel(
            name='ProviderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=60)),
                ('file_url', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prov_document',
            },
        ),
        migrations.CreateModel(
            name='ProviderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='providers.provider')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skills', to='services.serviceitem')),
            ],
            options={
                'db_table': 'prov_skill',
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['verification_status', 'city'], name='prov_provid_verific_1647be_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerskill',
            constraint=models.UniqueConstraint(fields=('provider', 'service_item'), name='ux_provider_skill'),
        ),
    ]
