# Generated by Django 5.1.15 on 2026-06-17 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=160)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('payout_method', models.CharField(default='bank_transfer', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='providers.provider')),
            ],
            options={
                'db_table': 'prov_bank_account',
            },
        ),
        migrations.CreateModel(
            name='ProviderVerificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='providers.provider')),
            ],
            options={
                'db_table': 'prov_verification_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCoverageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_coverage', to='geo.city')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_cities', to='providers.provider')),
            ],
            options={
                'db_table': 'prov_coverage_city',
                'constraints': [models.UniqueConstraint(fields=('provider', 'city'), name='ux_provider_coverage_city')],
            },
        ),
    ]
