# Generated by Django 5.1.15 on 2026-06-17 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=30)),
                ('gateway', models.CharField(max_length=60)),
                ('gateway_reference', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('checkout_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
            ],
            options={
                'db_table': 'fin_payment',
            },
        ),
        migrations.CreateModel(
            name='GatewayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=60)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gateway_events', to='finance.payment')),
            ],
            options={
                'db_table': 'fin_gateway_event',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released'), ('failed', 'Failed')], default='requested', max_length=30)),
                ('provider_notes', models.TextField(blank=True)),
                ('finance_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_payout',
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=60)),
                ('source_id', models.UUIDField()),
                ('entry_type', models.CharField(choices=[('payment_captured', 'Payment captured'), ('provider_earning', 'Provider earning'), ('commission', 'Commission'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('payout_requested', 'Payout requested'), ('payout_released', 'Payout released'), ('payout_failed', 'Payout failed'), ('hold', 'Hold'), ('hold_released', 'Hold released')], max_length=60)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='providers.provider')),
            ],
            options={
                'db_table': 'fin_wallet_ledger',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='fin_payment_booking_7699a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatewayevent',
            constraint=models.UniqueConstraint(fields=('gateway', 'event_id'), name='ux_gateway_event'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['provider', 'status'], name='fin_payout_provide_fb3e19_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['provider', '-created_at'], name='fin_wallet__provide_4d5442_idx'),
        ),
    ]
