# Generated by Django 5.1.15 on 2026-06-17 22:40

from django.conf import settings
from django.db import migrations, models
import uuid


def backfill_payout_idempotency_keys(apps, schema_editor):
    Payout = apps.get_model("finance", "Payout")
    for payout in Payout.objects.filter(idempotency_key__isnull=True):
        payout.idempotency_key = f"legacy-payout-{uuid.uuid4()}"
        payout.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.RunPython(backfill_payout_idempotency_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['source_type', 'source_id', 'entry_type'], name='fin_wallet__source__cf003c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='ck_payout_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_wallet_ledger_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.UniqueConstraint(fields=('provider', 'source_type', 'source_id', 'entry_type'), name='ux_wallet_ledger_source_entry'),
        ),
    ]
