# Generated by Django 5.1.15 on 2026-06-17 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience_role', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('ops', 'Operations')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aud_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'is_read', '-created_at'], name='aud_notific_recipie_5db8e9_idx'), models.Index(fields=['audience_role', 'is_read', '-created_at'], name='aud_notific_audienc_cd2506_idx'), models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='aud_notific_entity__50c2c4_idx')],
            },
        ),
    ]
