# Generated by Django 5.1.15 on 2026-06-17 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_snapshot', models.JSONField()),
                ('address_snapshot', models.JSONField()),
                ('requested_schedule', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_dispatch', 'Pending dispatch'), ('assigned', 'Assigned'), ('provider_accepted', 'Provider accepted'), ('provider_declined', 'Provider declined'), ('in_progress', 'In progress'), ('completed_by_provider', 'Completed by provider'), ('confirmed_completed', 'Confirmed completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending_dispatch', max_length=40)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customeraddress')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.serviceitem')),
            ],
            options={
                'db_table': 'book_booking',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='assigned', max_length=30)),
                ('assignment_reason', models.TextField(blank=True)),
                ('provider_response_reason', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('completion_evidence_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='providers.provider')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.booking')),
            ],
            options={
                'db_table': 'book_assignment',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
            ],
            options={
                'db_table': 'book_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'requested_schedule'], name='book_bookin_status_38f6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='book_bookin_custome_df24af_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['provider', 'status'], name='book_assign_provide_7f6bb1_idx'),
        ),
    ]
