from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from . import views

urlpatterns = [
    path("auth/customer/register", views.register_customer),
    path("auth/provider/register", views.register_provider),
    path("auth/login", views.login),
    path("auth/token/refresh", TokenRefreshView.as_view()),
    path("auth/otp/send", views.send_otp),
    path("auth/otp/verify", views.verify_otp),
    path("notifications", views.notifications),
    path("notifications/<uuid:notification_id>/read", views.mark_notification_read),
    path("uploads/request", views.request_upload),
    path("uploads/confirm", views.confirm_upload),
    path("uploads/<uuid:upload_id>", views.get_upload),
    path("customers/me", views.customer_me),
    path("customers/addresses", views.create_address),
    path("services/categories", views.service_categories),
    path("bookings", views.create_booking),
    path("customers/bookings", views.customer_bookings),
    path("bookings/<uuid:booking_id>", views.get_booking),
    path("bookings/<uuid:booking_id>/timeline", views.booking_timeline),
    path("bookings/<uuid:booking_id>/cancel", views.cancel_booking),
    path("admin/dispatch/queue", views.dispatch_queue),
    path("admin/providers/approved", views.approved_providers),
    path("admin/providers", views.admin_providers),
    path("admin/providers/<uuid:provider_id>/verification", views.update_provider_verification),
    path("providers/me", views.provider_me),
    path("providers/<uuid:provider_id>/timeline", views.provider_timeline),
    path("admin/dispatch/assign", views.assign_provider),
    path("admin/payments/simulate-capture", views.simulate_payment_capture),
    path("providers/jobs", views.provider_jobs),
    path("providers/jobs/<uuid:assignment_id>/accept", views.accept_job),
    path("providers/jobs/<uuid:job_id>/complete", views.complete_job),
    path("payments/checkout", views.create_checkout),
    path("payments/webhook", views.payment_webhook),
    path("providers/wallet", views.provider_wallet),
    path("providers/payouts", views.request_payout),
    path("providers/payouts/history", views.provider_payouts),
    path("complaints", views.create_complaint),
    path("customers/complaints", views.customer_complaints),
    path("complaints/<uuid:complaint_id>/timeline", views.complaint_timeline),
    path("admin/complaints", views.admin_complaints),
    path("admin/complaints/<uuid:complaint_id>/update", views.update_complaint),
    path("admin/payouts", views.admin_payouts),
    path("payouts/<uuid:payout_id>/timeline", views.payout_timeline),
    path("admin/payouts/<uuid:payout_id>/update", views.update_payout),
    path("admin/finance/summary", views.finance_summary),
    path("admin/finance/reconciliation", views.finance_reconciliation),
    path("admin/reports/executive", views.executive_report),
]
